### ISSUE TITLE
Memory is not always managed correctly

### ISSUE THREAD

**Issue by McCio** [JavaCardSpot-dev/KeepassNFCApplet#15]
Memory areas should be initialised before usage and bound checks should be done when managing it.

**Comment by aki8** [comment]
Necessary changes made to the applet

**Comment by McCio** [comment]
Further checks are missing, and some are currently wrongly written (missing short casts, fault induction checks...)

**Comment by McCio** [comment]
With last edits done, no more unchecked/unmanaged memory access/edit should be present.

@aki8, @viktech123, please check if some important check is still missing.

**Comment by aki8** [comment]
Checked the applet code and seems to be free from memory issues now, worth closing the issue.
