### ISSUE TITLE
Fault induction

### ISSUE THREAD

**Issue by McCio** [JavaCardSpot-dev/KeepassNFCApplet#16]
At least during sensitive and possibly-sensitive code execution, possible fault induction on both values and Instruction Pointer should be checked and managed correctly.

**Comment by McCio** [comment]
With last edits done, no more sensitive places should be left to check for fault induction.

@aki8, @viktech123, please check if some important check is still missing.

**Comment by viktech123** [comment]
Ok will check it

**Comment by viktech123** [comment]
It seems OK . All issues pertaining to fault induction checks are closed.
