### ISSUE TITLE
Integration of Security Issues in README

### ISSUE THREAD

**Issue by viktech123** [JavaCardSpot-dev/KeepassNFCApplet#7]
Explain in the README: 

- Absence of state management
- Absence of intialisation and clearing of sensitive data
- No use of custom exceptions
- No use of try-catch for exception handling
- No fault induction check
- No authentication and authorisation mechanisms
- No memory intialisation 
- No bound checking
- No secure protocol used
- Use of weak cryptographic algorithms

**Comment by aki8** [comment]
Readme file is updated with explainations

**Comment by aki8** [comment]
Readme file is updated with explanations

**Comment by aki8** [comment]
Readme file is updated with explainations

**Comment by aki8** [comment]
Readme file is updated with explanations
