### ISSUE TITLE
Add the test cases

### ISSUE THREAD

**Issue by viktech123** [JavaCardSpot-dev/KeepassNFCApplet#9]
Implement the test cases for the applet

**Comment by McCio** [comment]
Main test cases are setup, with current coverage of 82% (185 out of 225 significant lines in the applet).

**Comment by viktech123** [comment]
Added Test case for Verify User PIN

**Comment by viktech123** [comment]
Added Test case for Verification of Master PIN

**Comment by viktech123** [comment]
Added Test case for setting User PIN.
